### ISSUE TITLE
While using t.Parallel() I got error: name mismatch (try disabling parallel mode)

### ISSUE THREAD

**Issue by stamm** [tebeka/go2xunit#50] opened 2017-09-06 14:54 UTC
I have output from tests like this, but with more tests:
```
=== RUN   TestSuite
=== RUN   TestSuite1
--- PASS: TestSuite1 (0.01s)
--- PASS: TestSuite (0.35s)
=== RUN   Test1
=== RUN   Test2
--- PASS: Test1 (0.10s)
--- PASS: Test2 (0.10s)
```
When I run go2xunit I got error: `error: 7: name mismatch (try disabling parallel mode)`

I use `t.Parallel()` with testify

**Comment by tebeka** [comment] 2017-09-07 05:32
Thanks. `go2xunit` currently don't support working with `t.Parallel()`.

I plan to work on it when I find some time, however patches are always welcomed ;)

**Comment by tebeka** [comment] 2017-09-07 05:33
Duplicate of #29

**Closed by tebeka** 2017-09-07 05:33 UTC
